version: '3'

services:
  db:
    image: oracle/database:11.2.0.2-xe
    container_name: oracle11g
    shm_size: 1gb
    ports:
      - 1521:1521
      - 10001:10001
    volumes:
      - db-store:/opt/oracle/oradata
      - ./docker/script/setup:/docker-entrypoint-initdb.d/setup
    environment:
      - ORACLE_PWD=password

volumes:
  db-store:
